# task2
## 根据“一分一段”填充缺失的数据

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.getcwd()

'D:\\Study\\CollegeApplicationGuidance'

In [3]:
scoreRank2018DataPath = './data/2018广东省高考一分一段数据.txt'
scoreRank2019DataPath = './data/2019广东省高考一分一段数据.txt'
scoreRank2020DataPath = './data/2020广东省高考一分一段数据.txt'

In [4]:
scoreRank2018Data = {}
scoreRank2019Data = {}
scoreRank2020Data = {}

with open(scoreRank2018DataPath, 'r', encoding='utf-16') as f2018:
    linecount = 0
    columns = []
    while True:
        line = f2018.readline()
        linecount += 1
        if not line:
            break
        
        rowDataArr = line.strip().split('\t')

        if linecount==1:    
            columns = rowDataArr
            for (index, item) in enumerate(columns):
                scoreRank2018Data[item] = []   
        elif linecount>1:
            
            if not line.strip():
                continue
            for (index, item) in enumerate(rowDataArr):
                scoreRank2018Data[columns[index]].append(item)   
                
                
with open(scoreRank2019DataPath, 'r', encoding='utf-16') as f2019:
    linecount = 0
    columns = []
    while True:
        line = f2019.readline()
        linecount += 1
        if not line:
            break
        
        rowDataArr = line.strip().split('\t')

        if linecount==2:    
            columns = rowDataArr
            for (index, item) in enumerate(columns):
                scoreRank2019Data[item] = []   
        elif linecount>2:
            
            if not line.strip():
                continue
            for (index, item) in enumerate(rowDataArr):
                scoreRank2019Data[columns[index]].append(item)      
                
                
with open(scoreRank2020DataPath, 'r', encoding='utf-16') as f2020:
    linecount = 0
    columns = []
    while True:
        line = f2020.readline()
        linecount += 1
        if not line:
            break
        
        rowDataArr = line.strip().split('\t')

        if linecount==2:    
            columns = rowDataArr
            for (index, item) in enumerate(columns):
                scoreRank2020Data[item] = []   
        elif linecount>2:
            
            if not line.strip():
                continue
            for (index, item) in enumerate(rowDataArr):
                scoreRank2020Data[columns[index]].append(item)

In [5]:
df_scoreRank2018 = pd.DataFrame(scoreRank2018Data)
df_scoreRank2019 = pd.DataFrame(scoreRank2019Data)
df_scoreRank2020 = pd.DataFrame(scoreRank2020Data)

In [6]:
df_scoreRank2018

     分数段 分数段人数    累计人数
0    690    20      20
1    689     6      26
2    688     6      32
3    687     5      37
4    686     5      42
..   ...   ...     ...
536  154   144  329823
537  153   147  329970
538  152   151  330121
539  151   154  330275
540  150   124  330399

[541 rows x 3 columns]

In [7]:
scoreRankDict = {
    '2018': df_scoreRank2018,
    '2019': df_scoreRank2019,
    '2020': df_scoreRank2020
}

## 导入录取数据

In [8]:
admissionDataPath = './data/中山大学2018-2020年本科批次录取统计（广东）.txt'

In [9]:
admissionData = {}  
with open(admissionDataPath, 'r', encoding='utf-16') as f:
    linecount = 0
    columns = []  
    while True:
        line = f.readline()
        if not line:
            break
        linecount += 1
        
        if linecount==1:
            columns = line.strip().split('\t')
#             print(columns)
            for (index, item) in enumerate(columns):
                admissionData[item] = []
            
        if line.strip() and linecount!=1:
            rowDataArr = line.strip().split('\t')
            # 在缺失的数据中补上''作为填充
            while len(rowDataArr)<len(columns):
                rowDataArr.append('')
                
            for (index, item) in enumerate(rowDataArr):
                admissionData[columns[index]].append(item)

In [10]:
df_admission = pd.DataFrame(admissionData)

In [11]:
df_admission

,专业名称,所属学院,科类,2020最低分,2020平均分,2019最低分,2019平均分,2018最低分,2018平均分
0,新闻传播学类（含新闻学、传播学专业）,传播与设计学院,文科,614,617,618,621,621,624
1,法学,法学院,文科,616,619,617,620,619,624
2,工商管理,管理学院,文科,,,,,627,630
3,工商管理类（含工商管理、会计学专业）,管理学院,文科,617,619,623,625,,
4,会计学,管理学院,文科,,,,,614,626
...,...,...,...,...,...,...,...,...,...
112,临床医学,中山医学院,理科,653,660,625,632,626,636
113,临床医学（八年制）,中山医学院,理科,672,676,646,653,654,659
114,图书情报与档案管理类（含图书馆学、档案学专业）,资讯管理学院,理科,,,,,626,627
115,图书情报与档案管理类（含信息管理与信息系统、图书馆学、档案学专业）,资讯管理学院,理科,638,642,596,613,,
116,信息管理与信息系统,资讯管理学院,理科,,,,,629,631

In [12]:
columns_years = ['2020最低分', '2020平均分', '2019最低分', '2019平均分', '2018最低分', '2018平均分']
years = list(map(lambda x: x[:4], columns_years))
appendRankDataDict = {
    '2020最低分排位': [],
    '2020平均分排位': [],
    '2019最低分排位': [],
    '2019平均分排位': [],
    '2018最低分排位': [],
    '2018平均分排位': []
}
for (index_column, column) in df_admission.iteritems():
    if not index_column in columns_years:
        continue

    for (index_score, score) in enumerate(column):
        if not score:
            appendRankDataDict[index_column+'排位'].append('')
            continue
        tempDf = scoreRankDict[index_column[:4]]
        scoreRank = tempDf[tempDf['分数段']==score]['累计人数'].tolist()[0]
        appendRankDataDict[index_column+'排位'].append(scoreRank)

In [13]:
appendRankDataDict

{'2020最低分排位': ['13745',
  '12975',
  '',
  '12578',
  '',
  '17156',
  '16681',
  '',
  '',
  '15829',
  '13745',
  '17156',
  '11088',
  '',
  '17156',
  '',
  '',
  '14948',
  '',
  '',
  '',
  '15363',
  '',
  '',
  '15363',
  '17632',
  '14536',
  '13367',
  '16681',
  '',
  '15829',
  '6008',
  '8426',
  '',
  '8426',
  '2774',
  '8426',
  '',
  '4673',
  '',
  '7856',
  '5562',
  '2615',
  '',
  '',
  '',
  '1923',
  '6769',
  '8426',
  '',
  '2052',
  '',
  '1519',
  '1057',
  '4464',
  '5127',
  '',
  '',
  '3218',
  '8426',
  '8426',
  '',
  '8426',
  '',
  '7856',
  '5562',
  '6490',
  '6008',
  '7314',
  '',
  '1057',
  '',
  '6008',
  '',
  '5773',
  '5127',
  '4673',
  '6008',
  '8426',
  '',
  '',
  '',
  '3749',
  '1821',
  '',
  '2178',
  '3920',
  '',
  '',
  '',
  '8145',
  '5773',
  '',
  '',
  '3218',
  '',
  '5773',
  '4464',
  '5562',
  '7030',
  '5338',
  '',
  '',
  '5127',
  '3920',
  '4891',
  '',
  '',
  '8426',
  '2178',
  '4891',
  '2178',
  '3057',
  '915',
  '',
  '6008',
  ''],
 '2020平均分排位': ['12578',
  '11845',
  '',
  '11845',
  '',
  '16681',
  '15829',
  '',
  '',
  '14536',
  '12975',
  '16681',
  '9385',
  '',
  '16256',
  '',
  '',
  '13745',
  '',
  '',
  '',
  '14122',
  '',
  '',
  '14122',
  '16681',
  '13745',
  '11845',
  '15829',
  '',
  '15363',
  '5127',
  '7314',
  '',
  '7030',
  '2307',
  '7030',
  '',
  '3218',
  '',
  '7314',
  '4464',
  '2178',
  '',
  '',
  '',
  '1612',
  '5773',
  '7593',
  '',
  '1612',
  '',
  '1238',
  '841',
  '3567',
  '4673',
  '',
  '',
  '2774',
  '8145',
  '6769',
  '',
  '6769',
  '',
  '7030',
  '4464',
  '5338',
  '5562',
  '6490',
  '',
  '841',
  '',
  '5562',
  '',
  '4464',
  '3749',
  '3397',
  '5338',
  '6769',
  '',
  '',
  '',
  '3057',
  '1333',
  '',
  '1717',
  '3218',
  '',
  '',
  '',
  '7030',
  '4673',
  '',
  '',
  '2615',
  '',
  '4673',
  '3567',
  '4086',
  '6244',
  '4086',
  '',
  '',
  '3567',
  '3057',
  '3749',
  '',
  '',
  '6769',
  '1923',
  '3397',
  '2178',
  '2052',
  '655',
  '',
  '5127',
  ''],
 '2019最低分排位': ['4248',
  '4422',
  '',
  '3499',
  '',
  '6399',
  '6199',
  '',
  '',
  '5159',
  '5748',
  '6399',
  '2729',
  '',
  '6399',
  '',
  '',
  '5537',
  '',
  '',
  '',
  '5336',
  '',
  '',
  '5748',
  '6399',
  '5537',
  '4615',
  '5748',
  '',
  '5974',
  '5748',
  '6621',
  '9114',
  '',
  '3653',
  '7785',
  '',
  '4975',
  '',
  '7785',
  '4796',
  '2729',
  '',
  '',
  '',
  '2141',
  '8019',
  '9391',
  '',
  '2372',
  '',
  '1840',
  '1293',
  '4975',
  '5974',
  '',
  '',
  '3954',
  '9391',
  '9391',
  '',
  '6621',
  '',
  '9114',
  '6399',
  '5748',
  '5537',
  '8273',
  '',
  '1154',
  '',
  '9114',
  '9114',
  '',
  '',
  '4975',
  '9114',
  '5974',
  '',
  '',
  '',
  '3804',
  '1840',
  '',
  '2489',
  '3954',
  '',
  '',
  '8858',
  '',
  '6834',
  '',
  '',
  '3499',
  '',
  '5537',
  '4099',
  '6199',
  '7302',
  '5748',
  '',
  '',
  '4796',
  '3370',
  '4422',
  '',
  '',
  '9114',
  '2841',
  '6834',
  '4099',
  '3254',
  '1154',
  '',
  '9114',
  ''],
 '2019平均分排位': ['3804',
  '3954',
  '',
  '3254',
  '',
  '5748',
  '5748',
  '',
  '',
  '4248',
  '5159',
  '6199',
  '2606',
  '',
  '5974',
  '',
  '',
  '4975',
  '',
  '',
  '',
  '4615',
  '',
  '',
  '5336',
  '5974',
  '4796',
  '3804',
  '5336',
  '',
  '5537',
  '4248',
  '5974',
  '6834',
  '',
  '3111',
  '5974',
  '',
  '3954',
  '',
  '6834',
  '3954',
  '2253',
  '',
  '',
  '',
  '1579',
  '6199',
  '7302',
  '',
  '1741',
  '',
  '1579',
  '1084',
  '3499',
  '4975',
  '',
  '',
  '2974',
  '8858',
  '7785',
  '',
  '5537',
  '',
  '7538',
  '4422',
  '4422',
  '4796',
  '6621',
  '',
  '913',
  '',
  '5974',
  '7070',
  '',
  '',
  '3370',
  '6834',
  '5336',
  '',
  '',
  '',
  '2974',
  '1447',
  '',
  '1840',
  '3254',
  '',
  '',
  '6621',
  '',
  '4099',
  '',
  '',
  '2489',
  '',
  '4615',
  '3370',
  '4615',
  '6399',
  '4615',
  '',
  '',
  '3653',
  '3111',
  '2974',
  '',
  '',
  '6834',
  '1840',
  '5537',
  '3804',
  '2372',
  '771',
  '',
  '5159',
  ''],
 '2018最低分排位': ['4292',
  '4598',
  '3393',
  '',
  '5585',
  '5967',
  '5780',
  '4598',
  '4798',
  '',
  '5398',
  '5967',
  '',
  '2519',
  '5967',
  '5585',
  '4798',
  '',
  '5585',
  '5189',
  '5585',
  '',
  '4973',
  '5189',
  '',
  '5967',
  '4973',
  '4598',
  '5189',
  '5585',
  '',
  '5398',
  '6631',
  '',
  '',
  '3680',
  '6863',
  '3263',
  '',
  '5967',
  '7079',
  '4973',
  '',
  '2765',
  '3969',
  '2992',
  '1918',
  '6863',
  '6863',
  '3535',
  '',
  '2992',
  '2299',
  '2109',
  '3263',
  '5967',
  '5780',
  '3393',
  '',
  '6863',
  '6863',
  '6401',
  '',
  '6631',
  '7079',
  '5398',
  '5585',
  '6631',
  '',
  '1745',
  '',
  '1508',
  '4454',
  '',
  '',
  '',
  '5398',
  '',
  '6863',
  '3535',
  '1745',
  '2022',
  '',
  '',
  '2109',
  '2658',
  '4292',
  '6863',
  '6863',
  '',
  '',
  '',
  '4292',
  '3263',
  '',
  '5967',
  '',
  '4973',
  '5780',
  '6863',
  '6631',
  '4292',
  '4973',
  '',
  '3393',
  '',
  '6863',
  '2870',
  '6863',
  '3122',
  '4973',
  '3680',
  '3535',
  '917',
  '3535',
  '',
  '3122'],
 '2018平均分排位': ['3824',
  '3824',
  '2992',
  '',
  '3535',
  '5585',
  '5189',
  '3824',
  '3680',
  '',
  '4292',
  '5585',
  '',
  '2299',
  '5585',
  '5189',
  '4292',
  '',
  '4973',
  '4598',
  '4973',
  '',
  '3969',
  '4598',
  '',
  '5585',
  '4598',
  '3969',
  '4973',
  '5189',
  '',
  '4292',
  '5780',
  '',
  '',
  '2765',
  '6188',
  '2519',
  '',
  '4973',
  '6631',
  '3969',
  '',
  '2194',
  '3263',
  '2519',
  '1581',
  '5398',
  '6188',
  '1829',
  '',
  '1652',
  '1918',
  '1295',
  '2870',
  '5398',
  '3393',
  '2194',
  '',
  '6188',
  '6188',
  '5585',
  '',
  '5398',
  '6188',
  '4133',
  '4292',
  '5585',
  '',
  '1099',
  '',
  '865',
  '3824',
  '',
  '',
  '',
  '3824',
  '',
  '5585',
  '3122',
  '1357',
  '1652',
  '',
  '',
  '1829',
  '2109',
  '3393',
  '5967',
  '5780',
  '',
  '',
  '',
  '3535',
  '1829',
  '',
  '4598',
  '',
  '3969',
  '3969',
  '5967',
  '4973',
  '3535',
  '4292',
  '',
  '2992',
  '',
  '4973',
  '2415',
  '5585',
  '2022',
  '4292',
  '3680',
  '2299',
  '660',
  '3393',
  '',
  '2870']}

In [14]:
# 插入录取大表
df_admission['2020最低分排位'] = appendRankDataDict['2020最低分排位']
df_admission['2020平均分排位'] = appendRankDataDict['2020平均分排位']
df_admission['2019最低分排位'] = appendRankDataDict['2019最低分排位']
df_admission['2019平均分排位'] = appendRankDataDict['2019平均分排位']
df_admission['2018最低分排位'] = appendRankDataDict['2018最低分排位']
df_admission['2018平均分排位'] = appendRankDataDict['2018平均分排位']

In [15]:
df_admission

,专业名称,所属学院,科类,2020最低分,2020平均分,2019最低分,2019平均分,2018最低分,2018平均分,2020最低分排位,2020平均分排位,2019最低分排位,2019平均分排位,2018最低分排位,2018平均分排位
0,新闻传播学类（含新闻学、传播学专业）,传播与设计学院,文科,614,617,618,621,621,624,13745,12578,4248,3804,4292,3824
1,法学,法学院,文科,616,619,617,620,619,624,12975,11845,4422,3954,4598,3824
2,工商管理,管理学院,文科,,,,,627,630,,,,,3393,2992
3,工商管理类（含工商管理、会计学专业）,管理学院,文科,617,619,623,625,,,12578,11845,3499,3254,,
4,会计学,管理学院,文科,,,,,614,626,,,,,5585,3535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,临床医学,中山医学院,理科,653,660,625,632,626,636,3057,2052,3254,2372,3535,2299
113,临床医学（八年制）,中山医学院,理科,672,676,646,653,654,659,915,655,1154,771,917,660
114,图书情报与档案管理类（含图书馆学、档案学专业）,资讯管理学院,理科,,,,,626,627,,,,,3535,3393
115,图书情报与档案管理类（含信息管理与信息系统、图书馆学、档案学专业）,资讯管理学院,理科,638,642,596,613,,,6008,5127,9114,5159,,
116,信息管理与信息系统,资讯管理学院,理科,,,,,629,631,,,,,3122,2870

In [16]:
# 让排名跟分数挨在一起
df_admission = df_admission.reindex(columns=[
    '专业名称', '所属学院', '科类', 
    '2020最低分', '2020最低分排位',
    '2020平均分', '2020平均分排位',
    '2019最低分', '2019最低分排位',
    '2019平均分', '2019平均分排位',
    '2018最低分', '2018最低分排位',
    '2018平均分', '2018平均分排位'
])

In [17]:
df_admission

,专业名称,所属学院,科类,2020最低分,2020最低分排位,2020平均分,2020平均分排位,2019最低分,2019最低分排位,2019平均分,2019平均分排位,2018最低分,2018最低分排位,2018平均分,2018平均分排位
0,新闻传播学类（含新闻学、传播学专业）,传播与设计学院,文科,614,13745,617,12578,618,4248,621,3804,621,4292,624,3824
1,法学,法学院,文科,616,12975,619,11845,617,4422,620,3954,619,4598,624,3824
2,工商管理,管理学院,文科,,,,,,,,,627,3393,630,2992
3,工商管理类（含工商管理、会计学专业）,管理学院,文科,617,12578,619,11845,623,3499,625,3254,,,,
4,会计学,管理学院,文科,,,,,,,,,614,5585,626,3535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,临床医学,中山医学院,理科,653,3057,660,2052,625,3254,632,2372,626,3535,636,2299
113,临床医学（八年制）,中山医学院,理科,672,915,676,655,646,1154,653,771,654,917,659,660
114,图书情报与档案管理类（含图书馆学、档案学专业）,资讯管理学院,理科,,,,,,,,,626,3535,627,3393
115,图书情报与档案管理类（含信息管理与信息系统、图书馆学、档案学专业）,资讯管理学院,理科,638,6008,642,5127,596,9114,613,5159,,,,
116,信息管理与信息系统,资讯管理学院,理科,,,,,,,,,629,3122,631,2870

In [18]:
if not os.path.exists('./result'):
    os.mkdir('./result')
    
df_admission.to_excel('./result/中山大学近三年本科批次录取数据（含排名）.xlsx', index=False,encoding='utf-16')